services:
  shubhamlab:
    image: shubham/shubham
    hostname: localhost
    ports:
      - "8888:8888"
    volumes:
      - "./material:/home/shubham/material"
      - "./data:/data"
    environment:
      SHELL: /bin/bash
    networks:
      - shubhamnw
    depends_on:
      - "cluster_util_db"
  cluster_util_db:
    image: postgres:13
    ports:
      - "6432:5432"
    volumes:
      - ./cluster_util_db_scripts:/docker-entrypoint-initdb.d
    networks:
      - shubhamnw
    environment:
      POSTGRES_PASSWORD: shubham
  pysql:
    build:
      context: .
      dockerfile: images/pythonsql/DockerFile
    ports:
      - "8888:8888"
    volumes:
      - "./material:/home/shubham/material"
      - "./data:/data"
    environment:
      SHELL: /bin/bash
    networks:
      - shubhamnw
    depends_on:
      - "shubham.pg"
  shubham.pg:
      image: postgres
      ports:
        - "5432:5432"
      networks:
        - shubhamnw
      environment:
        POSTGRES_PASSWORD: shubham
networks:
  shubhamnw:
    name: shubhamnw